spring.application.name: resilience4j_annotation_demo_service

spring:
  profiles:
    active: service

server:
  port: ${PORT:8080}

backends:
  hosts:
    hotel-endpoint: localhost:9090
    airline-endpoint: localhost:7070

resilience4j.circuitbreaker:
  configs:
    default:
      failureRateThreshold: 50
      waitDurationInOpenState: 10000
      ringBufferSizeInClosedState: 10
      ringBufferSizeInHalfOpenState: 2

  backends:
    hotel:
      baseConfig: default
    airline:
      failureRateThreshold: 40
      waitDurationInOpenState: 5000
      ringBufferSizeInClosedState: 10
      ringBufferSizeInHalfOpenState: 2
