spring.application.name: resilience4j_demo_service
server:
  port: ${PORT:8080}

backends:
  hosts:
    hotel-endpoint: localhost:9090
    airline-endpoint: localhost:7070

resilience4j.circuitbreaker:
  configs:
    default:
      failureRateThreshold: 50
      waitInterval: 10000
      ringBufferSizeInClosedState: 10
      ringBufferSizeInHalfOpenState: 2

  backends:
    hotel_backend:
      baseConfig: default
    airline_backend:
      failureRateThreshold: 40
      waitInterval: 5000
      ringBufferSizeInClosedState: 10
      ringBufferSizeInHalfOpenState: 2

